In [1]:
import sys
sys.path.append('../../bats_transformer')

In [4]:
from argparse import ArgumentParser
import torch
import numpy as np

import pytorch_lightning as pl
import spacetimeformer as stf
import pandas as pd

from pytorch_lightning.loggers import WandbLogger
# from data import preprocess
import time
import tqdm
from itertools import chain
# from data.bats_dataset import *
from pytorch_lightning.callbacks import LearningRateMonitor

from itertools import chain
# from utils import *

In [25]:
# model_log_prefix = "../../bats_transformer/outputs/laci_daytime_10_18/model_41"
model_log_prefix = "../../bats_transformer/outputs/july_daytime_chunked_10_27/model_31"

In [26]:
truths = pd.read_csv(f"{model_log_prefix}_ground_truths.log")
predictions = pd.read_csv(f"{model_log_prefix}_predictions.log")
losses = pd.read_csv(f"{model_log_prefix}_losses.log")
truths

,Unnamed: 0,TimeIndex,TimeInFile,PrecedingIntrvl,HiFreq,Bndwdth,FreqMaxPwr,PrcntMaxAmpDur,FreqKnee,PrcntKneeDur,...,Amp4thQrtl,1st10kHzSlp,1st5to15kHzSlp,1st10kHzExp,1st5to15kHzExp,AmpK@start,MaxSegLngth,file_id,chirp_idx,model_id
0,0,1.693123,1.226714,0.053726,0.240524,-0.188106,0.621649,0.508016,-0.317605,1.360845,...,0.957563,-0.616636,-0.535707,-0.004901,-0.005559,-0.477442,0.0,8792.0,19.0,models/july_daytime_chunked_10_27/model_31
1,1,1.693123,1.226714,0.053726,0.240524,-0.188106,0.621649,0.508016,-0.317605,1.360845,...,0.957563,-0.616636,-0.535707,-0.004901,-0.005559,-0.477442,0.0,8792.0,18.0,models/july_daytime_chunked_10_27/model_31
2,2,1.693123,1.034134,-0.591655,-0.557718,-0.696253,-0.027887,-0.619573,-0.741466,0.715167,...,-0.744404,-0.055186,0.007525,-0.004901,-0.005559,-0.172704,0.0,8792.0,17.0,models/july_daytime_chunked_10_27/model_31
3,3,1.693123,1.034134,-0.591655,-0.557718,-0.696253,-0.027887,-0.619573,-0.741466,0.715167,...,-0.744404,-0.055186,0.007525,-0.004901,-0.005559,-0.172704,0.0,8792.0,16.0,models/july_daytime_chunked_10_27/model_31
4,4,1.693123,0.614583,-0.102056,0.223033,0.693049,-0.556669,0.823513,0.067160,0.132204,...,1.725759,1.100758,1.129234,-0.004900,-0.005556,0.280176,0.0,8792.0,15.0,models/july_daytime_chunked_10_27/model_31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4562,4562,1.693123,1.144180,2.612995,0.889044,0.515480,0.788126,0.161737,0.977902,-0.115859,...,-0.171246,-0.202391,-0.330055,-0.004901,-0.005560,-0.210365,0.0,9139.0,9.0,models/july_daytime_chunked_10_27/model_31
4563,4563,1.693123,1.144180,2.612995,0.889044,0.515480,0.788126,0.161737,0.977902,-0.115859,...,-0.171246,-0.202391,-0.330055,-0.004901,-0.005560,-0.210365,0.0,9139.0,8.0,models/july_daytime_chunked_10_27/model_31
4564,4564,1.693123,0.556121,-0.502637,0.707172,1.087214,0.593343,-0.564199,0.243102,0.107186,...,-1.080308,0.383947,0.372169,-0.004901,-0.005559,-0.456937,0.0,9139.0,7.0,models/july_daytime_chunked_10_27/model_31
4565,4565,1.693123,0.556121,-0.502637,0.707172,1.087214,0.593343,-0.564199,0.243102,0.107186,...,-1.080308,0.383947,0.372169,-0.004901,-0.005559,-0.456937,0.0,9139.0,6.0,models/july_daytime_chunked_10_27/model_31
4566,4566,1.693123,0.446075,-0.168820,0.519956,0.815793,0.381078,-0.599912,0.170067,-0.034679,...,-1.185427,0.591723,0.521670,-0.004901,-0.005559,-0.559711,0.0,9139.0,5.0,models/july_daytime_chunked_10_27/model_31

In [27]:
predicted_vals = losses.drop(["Unnamed: 0", "TimeIndex", "MaxSegLngth", "file_id", "chirp_idx", "model_id"], axis=1, errors="ignore")
predicted_vals

,TimeInFile,PrecedingIntrvl,HiFreq,Bndwdth,FreqMaxPwr,PrcntMaxAmpDur,FreqKnee,PrcntKneeDur,StartF,UpprKnFreq,...,Bndw32dB,Amp1stQrtl,Amp2ndQrtl,Amp3rdQrtl,Amp4thQrtl,1st10kHzSlp,1st5to15kHzSlp,1st10kHzExp,1st5to15kHzExp,AmpK@start
0,0.001826,0.039362,0.162441,0.002953,0.223986,0.002324,0.010502,0.169701,0.062841,0.001028,...,0.034705,0.522593,0.004582,0.030870,0.112763,0.014585,0.077563,0.052451,0.076075,0.166548
1,0.011979,0.205416,0.071876,0.065142,0.664134,0.288605,0.002355,1.360488,0.132613,0.719643,...,0.116047,1.841097,0.248583,0.095399,1.041856,0.385195,0.554867,0.026561,0.036206,0.000164
2,0.000597,0.037593,0.107900,0.059424,0.057495,0.004836,0.029021,0.054680,0.108089,0.056871,...,0.022334,0.006038,0.009696,0.095003,0.000289,0.157542,0.020640,0.024675,0.030605,0.005340
3,0.066384,0.006379,0.286247,0.686624,0.055269,0.589672,0.088641,0.684342,0.137125,0.312340,...,0.374912,7.910561,0.099161,0.744688,0.254087,0.188690,0.076487,0.016425,0.013003,0.003549
4,0.000225,0.011047,0.207874,0.054656,0.131348,0.310513,0.060722,0.023290,0.055692,0.001088,...,0.003039,0.053031,0.175217,0.000333,0.022934,0.776509,0.000982,0.039304,0.017080,0.089116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4562,0.015777,0.012222,0.171414,0.112589,0.308313,0.019925,0.070011,0.037263,0.577846,0.165525,...,0.029656,0.089283,0.059113,0.035666,0.153689,0.223985,0.003841,0.018520,0.040391,0.081806
4563,0.235043,7.811860,0.805779,0.031523,0.761219,1.012129,0.983091,0.015704,0.676388,0.826226,...,0.034366,1.213961,0.076345,0.185224,0.225427,0.102076,0.010996,0.039732,0.046663,0.086659
4564,0.003898,0.149898,0.531487,0.411110,0.103779,0.038953,0.189531,0.035801,0.168582,0.046348,...,0.007064,0.068736,0.111459,0.005014,0.086032,0.083313,0.297333,0.032412,0.035681,0.125040
4565,0.015863,0.015250,0.836420,1.241006,0.232831,0.000652,0.234273,0.010608,1.183293,0.701736,...,0.024590,0.050642,0.129558,0.002974,0.132196,0.068885,0.181112,0.030119,0.025223,0.023504
4566,0.007734,0.002420,0.320051,0.041133,0.195306,0.010179,0.005678,0.031569,0.004452,0.039807,...,0.007605,0.271220,0.121413,0.066741,0.163867,0.392066,0.135708,0.029791,0.011991,0.001258

In [28]:
# compute per-row average of numeric columns in `predicted_vals`
row_means = predicted_vals.select_dtypes(include="number").mean(axis=1)

# build new dataframe with row index and average value
avg_df = row_means.reset_index()
avg_df.columns = ["row_index", "avg_value"]

# show result
avg_df.head()

   row_index  avg_value
0          0   0.073237
1          1   0.480846
2          2   0.050629
3          3   0.413896
4          4   0.089345

In [29]:
print("mean squared error:", avg_df["avg_value"].mean())

mean squared error: 0.38255741675898375