In [22]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import pickle
import joblib

In [3]:
scaler = joblib.load(open('../../bats_transformer/data/daytime_files_new/splits/split_scaler.pkl', 'rb'))

In [4]:
scaler

StandardScaler()

In [5]:
scaler.feature_names_in_

array(['TimeInFile', 'PrecedingIntrvl', 'CallsPerSec', 'CallDuration',
       'Fc', 'HiFreq', 'LowFreq', 'Bndwdth', 'FreqMaxPwr',
       'PrcntMaxAmpDur', 'TimeFromMaxToFc', 'FreqKnee', 'PrcntKneeDur',
       'StartF', 'EndF', 'DominantSlope', 'SlopeAtFc', 'StartSlope',
       'EndSlope', 'SteepestSlope', 'LowestSlope', 'TotalSlope',
       'HiFtoKnSlope', 'KneeToFcSlope', 'CummNmlzdSlp', 'HiFtoFcExpAmp',
       'HiFtoFcDmp', 'KnToFcExpAmp', 'KnToFcDmp', 'HiFtoKnExpAmp',
       'HiFtoKnDmp', 'FreqLedge', 'LedgeDuration', 'FreqCtr', 'FBak32dB',
       'FFwd32dB', 'FBak20dB', 'FFwd20dB', 'FBak15dB  ', 'FFwd15dB',
       'FBak5dB', 'FFwd5dB', 'Bndw32dB', 'Bndw20dB', 'Bndw15dB',
       'Bndw5dB', 'DurOf32dB', 'DurOf20dB', 'DurOf15dB', 'DurOf5dB',
       'Amp1stQrtl', 'Amp2ndQrtl', 'Amp3rdQrtl', 'Amp4thQrtl',
       'Amp1stMean', 'Amp2ndMean', 'Amp3rdMean', 'Amp4thMean',
       'LnExpA_StartAmp', 'LnExpB_StartAmp', 'AmpStartLn60ExpC',
       'LnExpA_EndAmp', 'LnExpB_EndAmp', 'AmpEndLn60ExpC', 'AmpK@start',
       'AmpK@end', 'AmpKurtosis', 'AmpSkew', 'AmpVariance', 'AmpMoment',
       'AmpGausR2', 'Quality', 'HiFminusStartF', 'FcMinusEndF',
       'RelPwr2ndTo1st', 'RelPwr3rdTo1st', 'LdgToFcSlp', 'KnToFcDur',
       'UpprKnFreq', 'HiFtoUpprKnSlp', 'HiFtoUpprKnAmp', 'HiFtoUpprKnExp',
       'HiFtoKnAmp', 'HiFtoKnExp', 'HiFtoFcAmp', 'HiFtoFcExp',
       'UpprKnToKnAmp', 'UpprKnToKnExp', 'KnToFcAmp', 'KnToFcExp',
       'LdgToFcAmp', 'LdgToFcExp', 'PreFc250', 'PreFc500', 'PreFc1000',
       'PreFc250Residue', 'PreFc500Residue', 'PreFc1000Residue',
       'PreFc3000', 'PreFc3000Residue', 'KneeToFcResidue',
       'Kn-FcCurviness', 'meanKn-FcCurviness', 'Kn-FcCurvinessTrndSlp',
       'MinAccpQuality', 'Max#CallsConsidered'], dtype=object)

In [45]:
predictions = pd.read_csv("../../bats_transformer/outputs/sample_loss_output.log")

In [46]:
non_scaler_columns = {}

for idx, column in enumerate(predictions.columns):
    if column not in scaler.feature_names_in_:
        non_scaler_columns[idx] = predictions[column]
        predictions.drop(columns=[column], inplace=True)
non_scaler_columns

{0: 0          0
 1          1
 2          2
 3          3
 4          4
         ...
 2773    2773
 2774    2774
 2775    2775
 2776    2776
 2777    2777
 Name: Unnamed: 0, Length: 2778, dtype: int64,
 1: 0       1.710798
 1       1.710798
 2       1.710798
 3       1.710798
 4       1.710798
           ...
 2773    1.710798
 2774    1.710798
 2775    1.710798
 2776    1.710798
 2777    1.710798
 Name: TimeIndex, Length: 2778, dtype: float64,
 30: 0       4685.0
 1       4685.0
 2       4685.0
 3       4685.0
 4       4685.0
          ...
 2773    4815.0
 2774    4815.0
 2775    4815.0
 2776    4815.0
 2777    4815.0
 Name: file_id, Length: 2778, dtype: float64,
 31: 0       8.0
 1       7.0
 2       6.0
 3       5.0
 4       4.0
        ...
 2773    9.0
 2774    8.0
 2775    7.0
 2776    6.0
 2777    5.0
 Name: chirp_idx, Length: 2778, dtype: float64,
 32: 0       models_31
 1       models_31
 2       models_31
 3       models_31
 4       models_31
           ...
 2773    models_31
 2774    models_31
 2775    models_31
 2776    models_31
 2777    models_31
 Name: model_id, Length: 2778, dtype: object}

In [47]:

# predictions.drop(columns=['Unnamed: 0', 'TimeIndex', 'file_id', 'chirp_idx', 'model_id'], inplace=True)
predictions.columns

Index(['TimeInFile', 'PrecedingIntrvl', 'HiFreq', 'Bndwdth', 'FreqMaxPwr',
       'PrcntMaxAmpDur', 'FreqKnee', 'PrcntKneeDur', 'StartF', 'FreqCtr',
       'FFwd32dB', 'FFwd20dB', 'FFwd15dB', 'FBak5dB', 'FFwd5dB', 'Bndw32dB',
       'Amp1stQrtl', 'Amp2ndQrtl', 'Amp3rdQrtl', 'Amp4thQrtl', 'AmpK@start',
       'UpprKnFreq', 'HiFtoUpprKnAmp', 'HiFtoKnAmp', 'HiFtoFcAmp',
       'UpprKnToKnAmp', 'KnToFcAmp', 'LdgToFcAmp'],
      dtype='object')

In [44]:
all_features = list(scaler.feature_names_in_)
column_idxs = [] # indices of columns in predictions that are in scaler.feature_names_in_
for column in scaler.feature_names_in_:
    if column not in predictions.columns:
        predictions[column] = 0
    else:
        column_idxs.append(all_features.index(column))

In [33]:
predictions = predictions[scaler.feature_names_in_]

In [34]:
predictions

,TimeInFile,PrecedingIntrvl,CallsPerSec,CallDuration,Fc,HiFreq,LowFreq,Bndwdth,FreqMaxPwr,PrcntMaxAmpDur,...,PreFc500Residue,PreFc1000Residue,PreFc3000,PreFc3000Residue,KneeToFcResidue,Kn-FcCurviness,meanKn-FcCurviness,Kn-FcCurvinessTrndSlp,MinAccpQuality,Max#CallsConsidered
0,0.150988,0.046527,0,0,0,0.194979,0,0.733044,0.000281,1.836696,...,0,0,0,0,0,0,0,0,0,0
1,0.003546,0.365319,0,0,0,0.233285,0,1.130134,0.005998,1.831527,...,0,0,0,0,0,0,0,0,0,0
2,0.020443,0.441244,0,0,0,1.146308,0,0.761893,0.084553,3.543592,...,0,0,0,0,0,0,0,0,0,0
3,0.211942,0.086688,0,0,0,0.290400,0,0.541843,0.046895,1.382328,...,0,0,0,0,0,0,0,0,0,0
4,0.137741,0.166849,0,0,0,0.380169,0,0.000023,0.108300,1.306071,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,0.062160,0.000934,0,0,0,0.451942,0,0.513722,0.853023,0.137792,...,0,0,0,0,0,0,0,0,0,0
2774,0.300817,0.665693,0,0,0,0.238021,0,0.107219,0.216806,5.800500,...,0,0,0,0,0,0,0,0,0,0
2775,0.374191,0.077204,0,0,0,0.379859,0,0.113807,0.125684,0.823441,...,0,0,0,0,0,0,0,0,0,0
2776,0.051164,0.000220,0,0,0,0.216769,0,0.038736,0.011411,1.140799,...,0,0,0,0,0,0,0,0,0,0
2777,0.233139,0.571632,0,0,0,0.007521,0,0.002943,0.192168,0.190596,...,0,0,0,0,0,0,0,0,0,0

In [21]:
predictions_np = predictions.to_numpy()
predictions_np = predictions_np[:, :-1]
predictions_np

array([[1.7107978, 0.15098807, 0.046527106, ..., 0.008267463, 4685.0,
        8.0],
       [1.7107978, 0.003546194, 0.36531878, ..., 0.006710155, 4685.0,
        7.0],
       [1.7107978, 0.020442694, 0.44124392, ..., 0.008325806, 4685.0,
        6.0],
       ...,
       [1.7107978, 0.37419075, 0.07720432, ..., 0.17544831, 4815.0, 7.0],
       [1.7107978, 0.051164437, 0.00021994361, ..., 0.19964948, 4815.0,
        6.0],
       [1.7107978, 0.23313867, 0.5716325, ..., 0.17828299, 4815.0, 5.0]],
      dtype=object)

In [35]:
inverted_predictions = scaler.inverse_transform(predictions)

In [37]:
filtered_inverted_predictions = inverted_predictions[:, column_idxs]
filtered_inverted_predictions

array([[2.67436119e+03, 1.22674437e+02, 4.72550951e+01, ...,
        2.94362109e+04, 9.82632678e+03, 2.01071932e+06],
       [2.46196379e+03, 1.74280573e+02, 4.79389859e+01, ...,
        5.10534447e+04, 3.26366392e+04, 1.78941123e+06],
       [2.48630404e+03, 1.86571368e+02, 6.42395104e+01, ...,
        1.06770832e+05, 2.93444710e+04, 2.01901041e+06],
       ...,
       [2.99589583e+03, 1.27640477e+02, 5.05558208e+01, ...,
        6.52653336e+05, 3.04910356e+05, 2.57686881e+07],
       [2.53056025e+03, 1.15178213e+02, 4.76441163e+01, ...,
        6.02161434e+05, 2.51905423e+05, 2.92079017e+07],
       [2.79270325e+03, 2.07678729e+02, 4.39083385e+01, ...,
        8.03859185e+05, 2.54753538e+05, 2.61715228e+07]])

In [39]:
filtered_inverted_df = pd.DataFrame(filtered_inverted_predictions, columns=[predictions.columns[i] for i in column_idxs])
filtered_inverted_df

,TimeInFile,PrecedingIntrvl,HiFreq,Bndwdth,FreqMaxPwr,PrcntMaxAmpDur,FreqKnee,PrcntKneeDur,StartF,FreqCtr,...,Amp3rdQrtl,Amp4thQrtl,AmpK@start,UpprKnFreq,HiFtoUpprKnAmp,HiFtoKnAmp,HiFtoFcAmp,UpprKnToKnAmp,KnToFcAmp,LdgToFcAmp
0,2674.361194,122.674437,47.255095,28.015364,29.231166,96.108300,32.766769,41.750384,53.287600,33.254403,...,15945.341251,13829.157924,23.060365,39.593972,1.931501e+06,2.576251e+05,5.127591e+05,29436.210944,9826.326781,2.010719e+06
1,2461.963790,174.280573,47.938986,32.856216,29.284529,96.012626,33.497848,40.792060,46.515406,31.682977,...,18712.420081,14031.670812,23.254303,44.884293,2.521632e+06,1.152927e+06,5.516760e+05,51053.444739,32636.639191,1.789411e+06
2,2486.304044,186.571368,64.239510,28.367060,30.017740,127.701485,33.994107,77.076655,77.767998,31.671917,...,16074.636472,18749.279476,20.944878,47.765724,1.895711e+06,1.694817e+06,2.462738e+05,106770.831709,29344.471036,2.019010e+06
3,2762.168022,129.175705,48.958686,25.684469,29.666248,87.698338,32.586987,39.966934,47.570878,32.734444,...,21107.779883,12973.023992,24.595897,50.148588,2.168586e+06,1.331731e+06,2.298990e+05,35155.516885,21204.570147,2.107090e+06
4,2655.277824,142.152133,50.561358,19.079228,30.239381,86.286884,32.592977,40.417129,43.734869,31.809410,...,20905.299122,15367.242123,19.998138,38.646844,1.467374e+06,3.546704e+05,3.222381e+05,36161.879941,33688.973752,8.557268e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,2546.400128,115.293739,51.842750,25.341642,37.190386,64.663033,37.064154,40.843236,52.893495,33.803103,...,16119.916271,14676.145019,17.653446,53.321734,1.272140e+07,7.200592e+06,3.801895e+06,521939.127175,183825.116778,1.838113e+07
2774,2890.196982,222.905339,48.023535,20.386040,31.252141,169.474911,33.780120,56.766520,46.981876,33.729624,...,19481.703446,25478.729919,32.346881,43.692513,1.951949e+07,1.072335e+07,5.615973e+06,768433.983210,202695.060775,2.171605e+07
2775,2995.895830,127.640477,50.555821,20.466351,30.401643,77.353802,39.740455,40.202612,48.978366,34.617269,...,18208.251287,13090.861501,24.325870,52.982782,1.457857e+07,5.555794e+06,4.095760e+06,652653.335636,304910.356413,2.576869e+07
2776,2530.560253,115.178213,47.644116,19.551175,29.335054,83.227828,40.552393,596.952994,45.300374,32.409683,...,16765.955226,17536.359783,22.473392,38.648174,1.476561e+07,5.203940e+06,3.055596e+06,602161.434293,251905.423044,2.920790e+07
2777,2792.703247,207.678729,43.908338,19.114831,31.022179,65.640382,38.864753,47.371148,43.720685,31.729998,...,36003.569050,15796.096648,16.028030,37.623945,1.569437e+07,8.801304e+06,4.616638e+06,803859.185283,254753.538418,2.617152e+07

In [48]:
for idx, col_data in non_scaler_columns.items():
    filtered_inverted_df.insert(idx, col_data.name, col_data.values)
filtered_inverted_df

,Unnamed: 0,TimeIndex,TimeInFile,PrecedingIntrvl,HiFreq,Bndwdth,FreqMaxPwr,PrcntMaxAmpDur,FreqKnee,PrcntKneeDur,...,UpprKnFreq,HiFtoUpprKnAmp,HiFtoKnAmp,HiFtoFcAmp,UpprKnToKnAmp,KnToFcAmp,LdgToFcAmp,file_id,chirp_idx,model_id
0,0,1.710798,2674.361194,122.674437,47.255095,28.015364,29.231166,96.108300,32.766769,41.750384,...,39.593972,1.931501e+06,2.576251e+05,5.127591e+05,29436.210944,9826.326781,2.010719e+06,4685.0,8.0,models_31
1,1,1.710798,2461.963790,174.280573,47.938986,32.856216,29.284529,96.012626,33.497848,40.792060,...,44.884293,2.521632e+06,1.152927e+06,5.516760e+05,51053.444739,32636.639191,1.789411e+06,4685.0,7.0,models_31
2,2,1.710798,2486.304044,186.571368,64.239510,28.367060,30.017740,127.701485,33.994107,77.076655,...,47.765724,1.895711e+06,1.694817e+06,2.462738e+05,106770.831709,29344.471036,2.019010e+06,4685.0,6.0,models_31
3,3,1.710798,2762.168022,129.175705,48.958686,25.684469,29.666248,87.698338,32.586987,39.966934,...,50.148588,2.168586e+06,1.331731e+06,2.298990e+05,35155.516885,21204.570147,2.107090e+06,4685.0,5.0,models_31
4,4,1.710798,2655.277824,142.152133,50.561358,19.079228,30.239381,86.286884,32.592977,40.417129,...,38.646844,1.467374e+06,3.546704e+05,3.222381e+05,36161.879941,33688.973752,8.557268e+05,4685.0,4.0,models_31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,2773,1.710798,2546.400128,115.293739,51.842750,25.341642,37.190386,64.663033,37.064154,40.843236,...,53.321734,1.272140e+07,7.200592e+06,3.801895e+06,521939.127175,183825.116778,1.838113e+07,4815.0,9.0,models_31
2774,2774,1.710798,2890.196982,222.905339,48.023535,20.386040,31.252141,169.474911,33.780120,56.766520,...,43.692513,1.951949e+07,1.072335e+07,5.615973e+06,768433.983210,202695.060775,2.171605e+07,4815.0,8.0,models_31
2775,2775,1.710798,2995.895830,127.640477,50.555821,20.466351,30.401643,77.353802,39.740455,40.202612,...,52.982782,1.457857e+07,5.555794e+06,4.095760e+06,652653.335636,304910.356413,2.576869e+07,4815.0,7.0,models_31
2776,2776,1.710798,2530.560253,115.178213,47.644116,19.551175,29.335054,83.227828,40.552393,596.952994,...,38.648174,1.476561e+07,5.203940e+06,3.055596e+06,602161.434293,251905.423044,2.920790e+07,4815.0,6.0,models_31
2777,2777,1.710798,2792.703247,207.678729,43.908338,19.114831,31.022179,65.640382,38.864753,47.371148,...,37.623945,1.569437e+07,8.801304e+06,4.616638e+06,803859.185283,254753.538418,2.617152e+07,4815.0,5.0,models_31